### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.yolo.data.dataloaders'

### ISSUE THREAD

**Issue by liwenchao0615** [hdnh2006/YOLOv8API#1]
WARNING  'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING  'ultralytics.yolo.engine' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.engine' instead.
WARNING  'ultralytics.yolo.data' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.data' instead.
Note this warning may be related to loading older models. You can update your model to current structure with:
    import torch
    ckpt = torch.load("model.pt")  # applies to both official and custom models
    torch.save(ckpt, "updated-model.pt")

Traceback (most recent call last):
  File "F:\projectprogram\comparison_experiment\ZERRIDNet-comparision\YOLOv8API-main\segment_api.py", line 53, in <module>
    from ultralytics.yolo.data.dataloaders.v5loader import LoadImages, LoadScreenshots, LoadStreams
ModuleNotFoundError: No module named 'ultralytics.yolo.data.dataloaders'

**Comment by hdnh2006** [comment]
I need to update the API but running 'pip install 'ultralytics==8.0.134' should solve the problem.

Requirements has been updated.

**Comment by hdnh2006** [comment]
Hello! new format of `ultralytics` packages has been added and all the tasks are now supported in the same API, please check and let me know any issue!
